inferno/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.contrib.staticfiles.templatetags.staticfiles import static as static_url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('infernoapp.urls')),
    url(r'^', include('accountsvcs.urls')),
    url(r'^favicon\.ico$', RedirectView.as_view(url=static_url('fireball.png').replace('%', '%%'), permanent=True)),
]

infernoapp/urls.py
# coding=utf-8
from django.conf.urls import url, include
from rest_framework import routers
from rest_framework.schemas import get_schema_view
from rest_framework.authtoken import views as authtoken_views
from django.views.generic import TemplateView

from . import views, views_api

api_v1_router = routers.DefaultRouter()
api_v1_router.register(r'users', views_api.UserViewSet)
api_v1_router.register(r'tiers', views_api.TierViewSet)
api_v1_router.register(r'member-profiles', views_api.MemberProfileViewSet)
api_v1_router.register(r'session-templates', views_api.SessionTemplateViewSet)
api_v1_router.register(r'sessions', views_api.SessionViewSet)
api_v1_router.register(r'attendance-records', views_api.AttendanceRecordViewSet)
api_v1_router.register(r'session-template-tier-eligilities', views_api.TierEligibilityViewSet)
api_v1_router.register(r'tier-memberships', views_api.TierMembershipViewSet)
api_v1_router.register(r'calendar-events', views_api.CalendarEventSourceViewSet, base_name='calendar-events')
api_v1_router.register(r'calendar-events-for-member', views_api.CalendarMemberEventSourceViewSet, base_name='calendar-member-events')

api_v1_urls = [
    url('^members-for-session/(?P<session_id>[0-9]+)/$', views_api.MembersForSession.as_view(), name='members_for_session'),
    url('^profile/$', views_api.UserProfileView.as_view()),
    url('^api-token-auth/', authtoken_views.obtain_auth_token),
    url(r'^', include(api_v1_router.urls))
]

api_urls = [
    url(r'^v1/', include(api_v1_urls, namespace='v1'))
]

schema_view = get_schema_view(title='Inferno API')

urlpatterns = [
    url(r'^schema/$', schema_view),
    url(r'^api/', include(api_urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', views.home, name='home'),
    url(r'^sessions/$', views.SessionsView.as_view(), name='sessions'),
    url(r'^members/$', views.members, name='members'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^members/(?P<member_id>[0-9]+)/$', views.MemberView.as_view(), name='member'),
    url(r'^register/(?P<session_id>[0-9]+)/$', views.SessionView.as_view(), name='session'),
    url(r'^calendar.ics/$', views.ical, name='ical'),
    url(r'^submit-code/$', views.SubmitCodeView.as_view(), name='submit_code'),
    url(r'create-session/$', views.CreateSessionView.as_view(), name='create_session'),
    url(r'my-sessions/$', views.MySessions.as_view(), name='my_sessions'),
    url(r'my-sessions-calendar/$', TemplateView.as_view(template_name="infernoapp/my-calendar.html"), name='my_sessions_calendar'),
    url(r'^change_attending/$', views.ChangeAttendingView.as_view(), name='change_attending'),
    url(r'^commitments/$', views.CommitmentsView.as_view(), name='commitments'),
    url(r'^commitments/(?P<session_id>[0-9]+)/$', views.CommitmentView.as_view(), name='commitments'),
]

infernoapp/models.py
import random

from django.db import models
from django.conf import settings
from django.db.models import CASCADE
from django.db.models import SET_NULL
from django.utils import timezone
from datetime import timedelta


class Tier(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.name}'


class MemberProfile(models.Model):
    class Meta:
        ordering = ["user__name"]
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=CASCADE)

    # We would like to store a list of tiers, recoding the dates we joined and the dates we left (if any)

    def __str__(self):
        return f'{self.user.name}'


class TierMembership(models.Model):
    class Meta:
        ordering = ["tier"]
    member = models.ForeignKey(MemberProfile, on_delete=CASCADE)
    tier = models.ForeignKey(Tier, on_delete=CASCADE)
    joined = models.DateField(default=timezone.now)
    left = models.DateField(null=True, blank=True)

    def __str__(self):
        return f'{self.member} {self.tier} membership'

COLOURS = [
            "aliceblue",
            "antiquewhite",
            "aqua",
            "aquamarine",
            "azure",
            "beige",
            "bisque",
            "black",
            "blanchedalmond",
            "blue",
            "blueviolet",
            "brown",
            "burlywood",
            "cadetblue",
            "chartreuse",
            "chocolate",
            "coral",
            "cornflowerblue",
            "cornsilk",
            "crimson",
            "cyan",
            "darkblue",
            "darkcyan",
            "darkgoldenrod",
            "darkgray",
            "darkgreen",
            "darkkhaki",
            "darkmagenta",
            "darkolivegreen",
            "darkorange",
            "darkorchid",
            "darkred",
            "darksalmon",
            "darkseagreen",
            "darkslateblue",
            "darkslategray",
            "darkturquoise",
            "darkviolet",
            "deeppink",
            "deepskyblue",
            "dimgray",
            "dodgerblue",
            "firebrick",
            "floralwhite",
            "forestgreen",
            "fuchsia",
            "gainsboro",
            "ghostwhite",
            "gold",
            "goldenrod",
            "gray",
            "green",
            "greenyellow",
            "honeydew",
            "hotpink",
            "indianred",
            "indigo",
            "ivory",
            "khaki",
            "lavender",
            "lavenderblush",
            "lawngreen",
            "lemonchiffon",
            "lightblue",
            "lightcoral",
            "lightcyan",
            "lightgoldenrodyellow",
            "lightgray",
            "lightgreen",
            "lightpink",
            "lightsalmon",
            "lightseagreen",
            "lightskyblue",
            "lightslategray",
            "lightsteelblue",
            "lightyellow",
            "lime",
            "limegreen",
            "linen",
            "magenta",
            "maroon",
            "mediumaquamarine",
            "mediumblue",
            "mediumorchid",
            "mediumpurple",
            "mediumseagreen",
            "mediumslateblue",
            "mediumspringgreen",
            "mediumturquoise",
            "mediumvioletred",
            "midnightblue",
            "mintcream",
            "mistyrose",
            "moccasin",
            "navajowhite",
            "navy",
            "oldlace",
            "olive",
            "olivedrab",
            "orange",
            "orangered",
            "orchid",
            "palegoldenrod",
            "palegreen",
            "paleturquoise",
            "palevioletred",
            "papayawhip",
            "peachpuff",
            "peru",
            "pink",
            "plum",
            "powderblue",
            "purple",
            "rebeccapurple",
            "red",
            "rosybrown",
            "royalblue",
            "saddlebrown",
            "salmon",
            "sandybrown",
            "seagreen",
            "seashell",
            "sienna",
            "silver",
            "skyblue",
            "slateblue",
            "slategray",
            "snow",
            "springgreen",
            "steelblue",
            "tan",
            "teal",
            "thistle",
            "tomato",
            "turquoise",
            "violet",
            "wheat",
            "whitesmoke",
            "yellow",
            "yellowgreen"
]


def colour_picker():
    return random.choice(COLOURS)


class SessionTemplate(models.Model):
    name = models.CharField(max_length=200)
    default_leader = models.ForeignKey(MemberProfile, null=True, on_delete=SET_NULL)
    default_place = models.CharField(max_length=150)
    default_duration_hours = models.IntegerField(default=2)
    calendar_colour = models.CharField(max_length=50, default=colour_picker)

    def __str__(self):
        return f'Session Template: {self.name}'


class TierEligibility(models.Model):
    class Meta:
        verbose_name_plural = 'Tier Eligibilities'
    session_template = models.ForeignKey(SessionTemplate)
    tier = models.ForeignKey(Tier)
    required = models.BooleanField()

    def __str__(self):
        return f'{self.tier} eligibility for {self.session_template} ({"not " if not self.required else ""}required)'


def generate_code():
    return random.SystemRandom().randrange(999)


class Session(models.Model):
    class Meta:
        ordering = ["time"]

    template = models.ForeignKey(SessionTemplate)
    leader = models.ForeignKey(MemberProfile, null=True, related_name='leader_for_sessions')
    time = models.DateTimeField()
    place = models.CharField(max_length=150)
    last_modified = models.DateTimeField(auto_now=True)
    code = models.IntegerField(default=generate_code)
    duration_hours = models.IntegerField(default=2)

    attendances = models.ManyToManyField(MemberProfile, through='AttendanceRecord')
    commitments = models.ManyToManyField(MemberProfile, through='SessionCommitment', related_name='committed_sessions')

    @property
    def until(self):
        return self.time + timedelta(hours=self.duration_hours)

    def __str__(self):
        return f'Session {self.template.name} at {self.place} on {self.time} with {self.leader}'


class AttendanceRecord(models.Model):
    class Meta:
        ordering = ["member__user__name"]

    member = models.ForeignKey(MemberProfile, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    arrived_late = models.BooleanField(default=False)
    left_early = models.BooleanField(default=False)

    def __str__(self):
        return f'Attendance for {self.member}, {self.session}'


class SessionRole(models.Model):
    role = models.CharField(max_length=50)

    def __str__(self):
        return self.role


class SessionCommitment(models.Model):
    member = models.ForeignKey(MemberProfile, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    role = models.ForeignKey(SessionRole, on_delete=models.CASCADE)

infernoapp/templates/infernoapp/create-session.html
{% extends 'infernoapp/root.html' %}
{% block body %}
<h2>Create New Session</h2>
<form method="post">
	{% csrf_token %}
	<div class="form-group">
        <label for="templace">Session Template</label>
		<select class="form-control" id="template">
		{% for t in templates %}
			<option data-url="{{ t.url }}" value="{{t.pk}}" id="{{t.pk}}">{{t.name}}</option>
		{% endfor %}
		</select>
	</div>
    <div class="form-group">
        <label for="eligible-tiers">Eligible Tiers</label>
        <input type="text" class="form-control" readonly="readonly" id="eligible-tiers">
    </div>
    <div class="form-group">
        <label for="required-tiers">Required Tiers</label>
        <input type="text" class="form-control" readonly="readonly" id="required-tiers">
    </div>
	<div class="form-group">
		<label for="leader">Session Leader</label>
		<select class="form-control" id="leader">
		{% for m in members %}
			<option data-leaderid="{{m.pk}}" value="{{m.pk}}">{{m.user.name}}</option>
		{% endfor %}
		</select>
	</div>
	<div class="form-group">
		<label for="place">Place</label>
		<input type="text" class="form-control" id="place" required placeholder='Location'/>
	</div>
	<div class="form-group">
		<label for="time">Time</label>
		<input type="datetime-local" class="form-control" id="time">
	</div>
	<div class="form-group">
		<label for="duration">Duration (h)</label>
		<input type="number" class="form-control" id="duration">
	</div>
	<div class="form-group">
		<button type="button" id='addbutton' class="btn btn-default btn-primary btn-block">Add...</button>
	<div>
</form>
{% endblock %}
{% block postscripts %}
<script type='text/javascript'>
(function() {
	"use strict";
    function update() {
        var tl = document.getElementById("template");
        var templateID = tl.options[tl.selectedIndex].value;
        var templateURL = '/api/v1/session-templates/' + templateID + '/';

        $.ajax(templateURL, {
            method: 'GET'
        }).done(function (template, textStatus, jqXHR) {
            var default_leader_id = template.default_leader.id;
            var leader_box = $('#leader').find("[data-leaderid='"+default_leader_id+"']");
            //leader_box.attr('selected', 'selected');
	    leader_box.parent().get()[0].selectedIndex = leader_box.index();
            $('#place').val(template.default_place);
            $('#duration').val(template.default_duration_hours);

            var eligible = [];
            var required = [];
            for (var tieridx = 0; tieridx < template.tiereligibility_set.length; ++tieridx) {
                var tier = template.tiereligibility_set[tieridx];
                eligible.push(tier.tier.name);
                if (tier.required) {
                    required.push(tier.tier.name);
                }
            }

            $('#eligible-tiers').val(eligible.join(', '));
            $('#required-tiers').val(required.join(', '));



        }).fail(function (jqXHR, textStatus) {
            alert('Something bad happened: ' + jqXHR.responseText);
        });
	}


	$('#template').on('change', function(evt) {
	    update();
    });

    $('#addbutton').on('click', function(evt) {
        var tl = document.getElementById("template");
        var templateID = tl.options[tl.selectedIndex].value;
        var templateURL = '/api/v1/session-templates/' + templateID + '/';

        var ul = document.getElementById("leader");
        var memberID = ul.options[ul.selectedIndex].value;
        var memberURL = '/api/v1/member-profiles/' + memberID + '/';

        var where = $('#place').val();
        var when = $('#time').val();
        var duration = $('#duration').val();


        var new_session_url = '/api/v1/sessions/';
        var payload = {
            template: templateURL,
            leader: memberURL,
            time: when,
            place: where,
            duration_hours: duration
        };

        $.ajax(new_session_url,{
            method: 'POST',
            data: payload,
            headers: {
                "X-CSRFToken": "{{ csrf_token }}"
            }
        }).fail(function (jqXHR, textStatus) {
            alert('Something bad happened: ' + jqXHR.responseText);
        }).done(function(data, textStatus, jqXHR) {
            window.location = '{% url 'sessions' %}';
        });

    });

    update();
    var now = moment().format("YYYY-MM-DDTHH:mm");
    document.getElementById("time").value = now;

    })();

</script>
{% endblock %}

infernoapp/templates/infernoapp/home.html
{% extends 'infernoapp/root.html' %}
{% block body %}
    <div id="calendar"></div>

{% endblock %}

{% block postscripts %}
    <script type="text/javascript">
        var currentYear = new Date().getFullYear();

        $('#calendar').fullCalendar({
            eventSources: [
                {
                    url: '{% url 'v1:calendar-events-list' %}'
                }]
        });

    </script>
{% endblock %}

infernoapp/templates/infernoapp/member.html
{% extends 'infernoapp/root.html' %}
{% block body %}
    <h2>{{ member.user.name }}</h2>
    {% for tier in member.tiermembership_set.all %}
        <h3> <small class="text-muted">In {{ tier.tier.name }}
            {% if tier.left %}
                between {{ tier.joined }} and {{ tier.left }}
            {% else %}
                since {{ tier.joined }}
            {% endif %}
        </small></h3>
    {% endfor %}
    <h3>Past Attendance</h3>
        <table class="table table-hover table-responsive">
        <thead class="thead-inverse">
        <tr>
            <th>Session</th>

            <th>When</th>
            <th>Where</th>
            <th>Leader</th>

            <th>Required?</th>
            <th>Committed?</th>
            <th>Attended?</th>
            <th>Arrived Late?</th>
            <th>Left Early?</th>
        </tr>
        </thead>
        <tbody>
        {% for session in session_list %}
            <tr>
                <td><a href="{% url 'session' session.id %}" title="Go to session">{{ session.template.name }}</a></td>

                <td>{{ session.place }}</td>
                <td>{{ session.time|date:"l d M Y" }}</td>
                <td>{{ session.leader }}</td>

                <td>{% if session.required %}<span class="ion-checkmark-circled"></span>{% endif %}</td>
                <td>{% if session.response %}{{  session.response.role }}{% endif %}</td>
            {% if session.attendance %}
                <td><span class="ion-checkmark-circled"></span></td>
                <td>{% if session.attendance.arrived_late %}<span class="ion-checkmark-circled"></span>{% endif %}</td>
                <td>{% if session.attendance.left_early %}<span class="ion-checkmark-circled"></span>{% endif %}</td>
            {% else %}
                <td></td>
                <td></td>
                <td></td>
            {% endif %}

            </tr>
        {% endfor %}
        </tbody>
        </table>

{% endblock %}

infernoapp/templates/infernoapp/memberstats.html
{% extends 'infernoapp/root.html' %}
{% block body %}

    <h2>Member Attendance Statistics

        <div class="btn-group">
            <button type="button" class="btn btn-secondary">{% if days %}
                Last {{ days }} day{{ days|pluralize }}
            {% else %}
                All historical data
            {% endif %}</button>
            <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="?days=30">Last 30 days</a>
                <a class="dropdown-item" href="?days=60">Last 60 days</a>
                <a class="dropdown-item" href="?days=60">Last 90 days</a>
                <a class="dropdown-item" href="?days=120">Last 180 days</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="?">All data</a>
            </div>
        </div>

    </h2>

    <table class="table table-hover table-responsive">
        <thead class="thead-inverse">
        <tr>
            <th></th>

            <th colspan="4">Eligible</th>

            <th colspan="4">Required</th>

            <th colspan="4">Committed</th>

            <th colspan="3">Arrived Late</th>

            <th colspan="2">Left Early</th>
        </tr>
           <tr>
            <th>Member</th>

            <th>Sessions</th>
            <th>Attended</th>
            <th>Attendance</th>
               <th>&nbsp;</th>

            <th>Sessions</th>
            <th>Attended</th>
            <th>Attendance</th>
               <th>&nbsp;</th>

            <th>#</th>
            <th>Met</th>
            <th>Met %</th>
               <th>&nbsp;</th>

               <th>#</th>
               <th>%</th>
               <th>&nbsp;</th>

               <th>#</th>
               <th>%</th>
        </tr>
        </thead>
        <tbody>
        {% for member in members %}
            <tr>
                <td><a href="{% url 'member' member.member.pk %}">{{ member.member.user.name }}</a></td>

                <td>{{ member.eligible_count }}</td>
                <td>{{ member.eligible_attended_count }}</td>
                <td>{% widthratio member.eligible_attended_count member.eligible_count 100 %}%</td>
                <td>&nbsp;</td>

                <td>{{ member.required_count }}</td>
                <td>{{ member.required_attended_count }}</td>
                <td>{% widthratio member.required_attended_count member.required_count 100 %}%</td>
                <td>&nbsp;</td>

                <td>{{ member.committed_sessions.count }}</td>
                <td>{{ member.met_commitments.count }}</td>
                <td>{% widthratio member.met_commitments.count member.committed_sessions.count 100 %}%</td>
                <td>&nbsp;</td>

            <td>{{ member.late_sessions.count }}</td>
            <td>{% widthratio member.late_sessions.count member.required_attended_count 100 %}%</td>
                <td>&nbsp;</td>

            <td>{{ member.quitter_sessions.count }}</td>
            <td>{% widthratio member.quitter_sessions.count member.required_attended_count 100 %}%</td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

infernoapp/templates/infernoapp/my-sessions.html
{% extends 'infernoapp/root.html' %}
{% block body %}
    <h2>Upcoming Sessions for {{ user.name }}</h2>
    {% for tier in user.memberprofile.tiermembership_set.all %}
        <h3> <small class="text-muted">In {{ tier.tier.name }}
            {% if tier.left %}
                between {{ tier.joined }} and {{ tier.left }}
            {% else %}
                since {{ tier.joined }}
            {% endif %}
        </small></h3>
    {% endfor %}

    <p>For any event you will attend, change the drop-down on the right to the role you will be attending as. If you can't see any drop-downs and you're using a phone, scroll right or use landscape mode!</p>
    <p>If you can't make an event, leave it as 'no commitment'.</p>
    <p>Events added or changed within the last {{ recency_cutoff }} days are highlighted.</p>


    <table class="table table-hover table-responsive">
        <thead class="thead-inverse">
        <tr>
            <th>Session</th>

            <th>Where</th>
            <th>Date</th>
            <th>From</th>
            <th>To</th>
            <th>With</th>
            <th>Required?</th>
            <th>Commit to attending as</th>

        </tr>
        </thead>
        <tbody>
        {% for session in sessions %}
            <tr>
                <td><a href="{% url 'session' session.pk %}">{{ session.template.name }}</a></td>

                <td>{{ session.place }}</td>
                <td>{{ session.time|date:'D, j N' }}</td>
                <td>{{ session.time|time:'H:i' }}</td>
                <td>{{ session.until|time:'H:i' }}</td>
                <td>{{ session.leader }}</td>
                <td style="text-align: center;">{% if session.required %}<span class="ion-checkmark-circled"></span>{% endif %}</td>
                <td>
                    <select title='Commitment' id="{{ session.pk }}"
                            class='form-control attending_changer'>
                        <option value="null">(no commitment)</option>
                        {% for role in roles %}
                            <option value="{{ role.id }}"
                                    {% if session.response %}
                                        {% if role.id == session.response.role.id %}
                                    selected
                                        {% endif %}

                                    {% endif %}
                            >
                                {{ role }}
                            </option>
                        {% endfor %}
                    </select>

                </td>

            </tr>
        {% empty %}
            <tr>
                <td>No sessions!</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block postscripts %}
    <script type="text/javascript">
        $(".attending_changer").change(function () {
            var new_value = $(this).val();
            var payload = {
                'event_id': $(this).attr('id'),
                'new_status': new_value,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            };
            $.ajax('{% url 'change_attending' %}', {
                method: 'POST',
                data: payload
            }).done(function (data) {

            }).fail(function () {
                alert('nope');
            });
        });
    </script>
{% endblock %}

infernoapp/templates/infernoapp/session.html
{% extends 'infernoapp/root.html' %}
{% block body %}
    <div id="session" data-sessionid="{{ session_id }}">
        <h2><span id="session-name"></span>
            <small class="text-muted">At <span id="session-place"></span>, <span id="session-time"></span> with <span
                    class="session-leader"></span></small>
        </h2>

        <div class="card">
            <h4 class="card-header">To mark yourself as here, enter the code given to you from <span
                    class="session-leader"></span> (valid until <span class="session-code-validity-expires"></span>)</h4>
            <div class="card-block">
                <form class="form form-inline">
                        <input class="form-control" type="number" required placeholder="Session Code" id="code">
                        <button type="button" class="btn btn-outline-primary" id="submitcode">I am here!</button>
                </form>
            </div>
            <div class="message"></div>
        </div>
    <div class="card">
        <h5 class="card-header">Coming soon: Have your session leader scan this...</h5>
        <div class="card-block">
            <a class='pull-right' rel='nofollow' href='http://www.qrcode-generator.de' border='0' style='cursor:default'></a><img src='https://chart.googleapis.com/chart?cht=qr&chl={{ request.build_absolute_uri|urlencode }}&chs=180x180&choe=UTF-8&chld=L|2' alt=''>
        </div>
    </div>
    </div>

{% endblock %}

{% block postscripts %}
    <script type="text/javascript">
        (function () {
            "use strict";
            var session_id = {{ session_id }};
            var session_url = '{% url 'v1:session-detail' session_id %}';
            var members_for_session_url = '{% url 'v1:members_for_session' session_id %}';
            var submit_code_url = '{% url 'submit_code' %}';

            $('#submitcode').on('click', function(event) {
                var code = $('#code').val();
                event.stopPropagation();
                if (code.length < 1) return;
                $.ajax(submit_code_url, {
                    method: 'POST',
                    data: {
                        'code': code,
                        'session_id': session_id
                    },
                    headers: {
                        "X-CSRFToken": "{{ csrf_token }}"
                    }
                }).done(function (data, textStatus, jqXHR) {
                    $(".alert").alert('close');
                        $('.message').after().append(
                            '<div class="alert alert-success alert-dismissible fade show" role="alert"> ' +
                            '<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
                            '<span aria-hidden="true">&times;</span>' +
                            '</button>' +
                            '<strong>Tweet!</strong> <span class="error-text"></span>' +
                            '</div>');

                        $('.error-text').html("Thanks!");
                        $(".alert").alert();
                }).fail(function (jqXHR, textStatus) {
                        $(".alert").alert('close');
                        $('.message').after().append(
                            '<div class="alert alert-warning alert-dismissible fade show" role="alert"> ' +
                            '<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
                            '<span aria-hidden="true">&times;</span>' +
                            '</button>' +
                            '<strong>Tweet!</strong> <span class="error-text"></span>' +
                            '</div>');

                        $('.error-text').html(jqXHR.responseText);
                        $(".alert").alert();
                });

            });

            $.ajax(session_url, {
                method: 'GET'
            }).done(function (session, textStatus, jqXHR) {

                var when = moment(session.time);
                var code_expires = moment(session.code_validity_ends);


                $('#session-name').html(session.template.name);
                $('#session-place').html(session.place);
                $('#session-time').html(when.calendar());
                $('.session-leader').html(session.leader.user.name);
                $('.session-code').html(session.code);
                $('.session-code-validity-expires').html(code_expires.calendar());

            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert(textStatus);
            }).always(function (data_or_jqXHR, textStatus, jqXHR_or_errorThrown) {

            });


        })();
    </script>
{% endblock %}

infernoapp/templates/infernoapp/sessionstats.html
{% extends 'infernoapp/root.html' %}
{% block body %}
    <h2>Session Attendance Statistics</h2>

    <table class="table table-hover table-responsive">
        <thead class="thead-inverse">
        <tr>
            <th>Session</th>

            <th>Where</th>
            <th>Date</th>
            <th>From</th>
            <th>To</th>
            <th>Who</th>

            <th>Eligible Tiers</th>
            <th>Eligible Members</th>

            <th>Required Tiers</th>
            <th>Required Members</th>
            <th>Pledges Made</th>
            <th>Pledges Met</th>
            <th>Attended</th>

        </tr>
        </thead>
        <tbody>
        {% for session in sessions %}
            <tr>
                <td><a href="{% url 'session' session.session.pk %}">{{ session.session.template.name }}</a></td>

                <td>{{ session.session.place }}</td>
                <td>{{ session.session.time|date:'D, j N' }}</td>
                <td>{{ session.session.time|time:'H:i' }}</td>
                <td>{{ session.session.until|time:'H:i' }}</td>
                <td>{{ session.session.leader }}</td>

                <td>
                    {% for el in session.session.template.tiereligibility_set.all %}
                        {{ el.tier.name }}{% if not forloop.last %},{% endif %}
                    {% endfor %}
                </td>

                <td>
                    {{ session.eligible_count }}
                </td>
                <td>
                    {% for el in session.session.template.tiereligibility_set.all %}
                        {% if el.required %}
                        {{ el.tier.name }}
                        {% endif %}
                    {% endfor %}
                </td>
                <td>{{ session.required_count }}

                </td>

            <td>{{ session.committed.count }}</td>
            <td>{{ session.met_commitments.count }}</td>
                <td>
                    {{ session.eligible_attended_count }}
                </td>
            </tr>
        {% empty %}
            <tr>
                <td>No sessions!</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}